//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace SiyafundaApplication
{
    public partial class frmCreateQuiz
    {

        /// <summary>
        /// txtQuizTitle control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtQuizTitle;

        /// <summary>
        /// ddlModules control.
        /// </summary>
        protected global::System.Web.UI.WebControls.DropDownList ddlModules;

        /// <summary>
        /// txtDuration control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtDuration;

        /// <summary>
        /// txtDueDate control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtDueDate;

        /// <summary>
        /// lblQuestionsSubmitted control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label lblQuestionsSubmitted;

        /// <summary>
        /// btnAddMCQ control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Button btnAddMCQ;

        /// <summary>
        /// btnAddFillBlank control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Button btnAddFillBlank;

        /// <summary>
        /// btnAddLongForm control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Button btnAddLongForm;

        /// <summary>
        /// btnSubmitQuiz control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Button btnSubmitQuiz;

        /// <summary>
        /// lblMessage control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label lblMessage;
    }
}
