//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace SiyafundaApplication
{
    public partial class frmFBAnswer
    {
        /// <summary>
        /// form1 control.
        /// </summary>
        protected global::System.Web.UI.HtmlControls.HtmlForm form1;

        /// <summary>
        /// lblQuestionNumber control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label lblQuestionNumber;

        /// <summary>
        /// lblQuestionText control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label lblQuestionText;

        /// <summary>
        /// txtAnswer control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtAnswer;

        /// <summary>
        /// lblTimer control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label lblTimer;

        /// <summary>
        /// lblMessage control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label lblMessage;

        /// <summary>
        /// btnNext control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Button btnNext;
    }
}
