//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace SiyafundaApplication
{
    public partial class frmQuizCompleted
    {
        /// <summary>
        /// form1 control.
        /// </summary>
        protected global::System.Web.UI.HtmlControls.HtmlForm form1;

        /// <summary>
        /// lblCompletionMessage control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label lblCompletionMessage;

        /// <summary>
        /// lblScore control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label lblScore;

        /// <summary>
        /// lblPreliminaryMessage control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label lblPreliminaryMessage;

        /// <summary>
        /// btnReturn control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Button btnReturn;
    }
}
