//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace SiyafundaApplication
{
    public partial class frmTakeQuiz
    {
        /// <summary>
        /// form1 control.
        /// </summary>
        protected global::System.Web.UI.HtmlControls.HtmlForm form1;

        /// <summary>
        /// ddlModules control.
        /// </summary>
        protected global::System.Web.UI.WebControls.DropDownList ddlModules;

        /// <summary>
        /// ddlQuizzes control.
        /// </summary>
        protected global::System.Web.UI.WebControls.DropDownList ddlQuizzes;

        /// <summary>
        /// lblQuizTitle control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label lblQuizTitle;

        /// <summary>
        /// lblDuration control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label lblDuration;

        /// <summary>
        /// lblCreateDate control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label lblCreateDate;

        /// <summary>
        /// lblDueDate control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label lblDueDate;

        /// <summary>
        /// btnStartQuiz control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Button btnStartQuiz;

        /// <summary>
        /// lblWarning control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label lblWarning;

        /// <summary>
        /// lblModuleError control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label lblModuleError;

        /// <summary>
        /// lblQuizError control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label lblQuizError;

        /// <summary>
        /// lblMessage control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label lblMessage;
    }
}
