//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SiyafundaApplication
{


    public partial class frmUploadFiles
    {

        /// <summary>
        /// ModuleLabel control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label ModuleLabel;

        /// <summary>
        /// ModuleDropDown control.
        /// </summary>
        protected global::System.Web.UI.WebControls.DropDownList ModuleDropDown;

        /// <summary>
        /// FileUploadControl control.
        /// </summary>
        protected global::System.Web.UI.WebControls.FileUpload FileUploadControl;

        /// <summary>
        /// txtTitle control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtTitle;

        /// <summary>
        /// txtDesc control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtDesc;

        /// <summary>
        /// UploadButton control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Button UploadButton;

        /// <summary>
        /// lblError control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label lblError;
    }
}

