ALTER TABLE [Users] ADD 	[user_id] int IDENTITY(1,1) NOT NULL;
ALTER TABLE [Users] ADD 	[Name] nvarchar(max) NOT NULL DEFAULT '30';
ALTER TABLE [Users] ADD 	[Surname] nvarchar(max) NOT NULL DEFAULT '30';
ALTER TABLE [Users] ADD 	[Username] nvarchar(max) NOT NULL UNIQUE DEFAULT '50';
ALTER TABLE [Users] ADD 	[Email] nvarchar(max) NOT NULL DEFAULT '60';
ALTER TABLE [Users] ADD 	[Password] nvarchar(max) NOT NULL DEFAULT '255';
ALTER TABLE [Users] ADD 	[Role_id] int NOT NULL DEFAULT '20';
ALTER TABLE [Resources] ADD 	[resource_id] int NOT NULL;
ALTER TABLE [Resources] ADD 	[user_id] int NOT NULL;
ALTER TABLE [Resources] ADD 	[module_id] int NOT NULL;
ALTER TABLE [Resources] ADD 	[title] nvarchar(max) NOT NULL DEFAULT '100';
ALTER TABLE [Resources] ADD 	[description] nvarchar(max) NOT NULL;
ALTER TABLE [Resources] ADD 	[upload_date] datetime NOT NULL;
ALTER TABLE [Files] ADD 	[file_id] int NOT NULL;
ALTER TABLE [Files] ADD 	[resource_id] int NOT NULL;
ALTER TABLE [Files] ADD 	[file_path] nvarchar(max) NOT NULL DEFAULT '255';
ALTER TABLE [Files] ADD 	[file_type] nvarchar(max) NOT NULL DEFAULT '50';
ALTER TABLE [Files] ADD 	[file_size] int NOT NULL;
ALTER TABLE [Reviews] ADD 	[review_id] int NOT NULL;
ALTER TABLE [Reviews] ADD 	[resource_id] int NOT NULL;
ALTER TABLE [Reviews] ADD 	[user_id] int NOT NULL;
ALTER TABLE [Reviews] ADD 	[rating] int NOT NULL;
ALTER TABLE [Reviews] ADD 	[comment] nvarchar(max) NOT NULL;
ALTER TABLE [Announcements] ADD 	[announcement_id] int NOT NULL;
ALTER TABLE [Announcements] ADD 	[user_id] int NOT NULL;
ALTER TABLE [Announcements] ADD 	[module_id] int NOT NULL;
ALTER TABLE [Announcements] ADD 	[title] nvarchar(max) NOT NULL DEFAULT '100';
ALTER TABLE [Announcements] ADD 	[content] nvarchar(max) NOT NULL;
ALTER TABLE [Announcements] ADD 	[created_at] datetime NOT NULL;
ALTER TABLE [FAQs] ADD 	[faq_id] int IDENTITY(1,1) NOT NULL;
ALTER TABLE [FAQs] ADD 	[module_id] int NOT NULL;
ALTER TABLE [FAQs] ADD 	[user_id] int NOT NULL;
ALTER TABLE [FAQs] ADD 	[created_at] datetime NOT NULL;
ALTER TABLE [FAQs] ADD 	[question] nvarchar(max) NOT NULL;
ALTER TABLE [FAQs] ADD 	[answer] nvarchar(max) NOT NULL;
ALTER TABLE [Modules] ADD 	[module_id] int IDENTITY(1,1) NOT NULL;
ALTER TABLE [Modules] ADD 	[title] nvarchar(max) NOT NULL DEFAULT '100';
ALTER TABLE [Modules] ADD 	[description] nvarchar(max) NOT NULL;
ALTER TABLE [Modules] ADD 	[created_at] datetime NOT NULL;
ALTER TABLE [Modules] ADD 	[educator_id] int NOT NULL;
ALTER TABLE [Gradebook] ADD 	[module_id] int NOT NULL;
ALTER TABLE [Gradebook] ADD 	[gradebook_id] int NOT NULL;
ALTER TABLE [Gradebook] ADD 	[user_id] int NOT NULL;
ALTER TABLE [Gradebook] ADD 	[grade] float(53) NOT NULL;
ALTER TABLE [Gradebook] ADD 	[comments] nvarchar(max) NOT NULL;
ALTER TABLE [Quizzes] ADD 	[quiz_id] int NOT NULL;
ALTER TABLE [Quizzes] ADD 	[module_id] int NOT NULL;
ALTER TABLE [Quizzes] ADD 	[duration] int NOT NULL;
ALTER TABLE [Quizzes] ADD 	[title] nvarchar(max) NOT NULL DEFAULT '100';
ALTER TABLE [Quizzes] ADD 	[created_at] datetime NOT NULL;
ALTER TABLE [Quizzes] ADD 	[due_date] datetime NOT NULL;
ALTER TABLE [QuizQuestions] ADD 	[question_id] int NOT NULL;
ALTER TABLE [QuizQuestions] ADD 	[quiz_id] int NOT NULL;
ALTER TABLE [QuizQuestions] ADD 	[question_text] nvarchar(max) NOT NULL;
ALTER TABLE [QuizQuestions] ADD 	[correct_answer] nvarchar(max) NOT NULL DEFAULT '255';
ALTER TABLE [QuizQuestions] ADD 	[points] int NOT NULL;
ALTER TABLE [QuizResponses] ADD 	[response_id] int NOT NULL;
ALTER TABLE [QuizResponses] ADD 	[user_id] int NOT NULL;
ALTER TABLE [QuizResponses] ADD 	[question_id] int NOT NULL;
ALTER TABLE [QuizResponses] ADD 	[selected_answer] nvarchar(max) NOT NULL DEFAULT '255';
ALTER TABLE [QuizResponses] ADD 	[submitted_at] datetime NOT NULL;
ALTER TABLE [UserSessions] ADD 	[session_id] int NOT NULL;
ALTER TABLE [UserSessions] ADD 	[user_id] int NOT NULL;
ALTER TABLE [UserSessions] ADD 	[session_token] nvarchar(max) NOT NULL DEFAULT '255';
ALTER TABLE [UserSessions] ADD 	[created_at] datetime NOT NULL;
ALTER TABLE [UserSessions] ADD 	[expires_at] datetime NOT NULL;
ALTER TABLE [Roles] ADD 	[role_id] int IDENTITY(1,1) NOT NULL UNIQUE DEFAULT 0;
ALTER TABLE [Roles] ADD 	[role_name] nvarchar(15) NOT NULL;
ALTER TABLE [Roles] ADD 	[role_desc] nvarchar(50) NOT NULL;
ALTER TABLE [Stu_To_Module] ADD 	[stu_to_mod_id] int IDENTITY(1,1) NOT NULL UNIQUE;
ALTER TABLE [Stu_To_Module] ADD 	[module_id] int NOT NULL;
ALTER TABLE [Stu_To_Module] ADD 	[user_id] int NOT NULL;
ALTER TABLE [DocStatuses] ADD 	[status_id] int IDENTITY(1,1) NOT NULL UNIQUE;
ALTER TABLE [DocStatuses] ADD 	[status_name] nvarchar(max) NOT NULL;
ALTER TABLE [Res_to_status] ADD 	[res_to_status_id] int IDENTITY(1,1) NOT NULL UNIQUE;
ALTER TABLE [Res_to_status] ADD 	[status_id] int NOT NULL;
ALTER TABLE [Res_to_status] ADD 	[resource_id] int NOT NULL;
ALTER TABLE [Res_to_status] ADD 	[user_id] int NOT NULL;
ALTER TABLE [Res_to_status] ADD 	[feedback] nvarchar(max) NOT NULL;
ALTER TABLE [TimeTable] ADD 	[time_table_id] int IDENTITY(1,1) NOT NULL UNIQUE;
ALTER TABLE [TimeTable] ADD 	[user_id] int NOT NULL;
ALTER TABLE [TimeTable] ADD 	[module_id] int NOT NULL;
ALTER TABLE [TimeTable] ADD 	[day_id] int NOT NULL;
ALTER TABLE [TimeTable] ADD 	[class_start_time] datetime NOT NULL;
ALTER TABLE [TimeTable] ADD 	[class_end_time] datetime NOT NULL;
ALTER TABLE [DaysOfTheWeek] ADD 	[day_id] int IDENTITY(1,1) NOT NULL UNIQUE;
ALTER TABLE [DaysOfTheWeek] ADD 	[day_name] nvarchar(max) NOT NULL;