# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy ASP.NET Framework app to Azure Web App - Siyafunda

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up .NET Framework
        run: |
          choco install dotnetfx --version=4.8.1 --params "'/InstallDir:C:\Program Files\dotnetfx'"

      - name: Build solution
        run: |
          "C:\Program Files\dotnetfx\MSBuild\14.0\Bin\MSBuild.exe" ./SiyafundaApplication/SiyafundaApplication.sln /p:Configuration=Release

      - name: Publish
        run: |
          "C:\Program Files\dotnetfx\MSBuild\14.0\Bin\MSBuild.exe" ./SiyafundaApplication/SiyafundaApplication/SiyafundaApplication.csproj /p:Configuration=Release /p:OutputPath="C:\Program Files\dotnet\myapp"

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: .net-app
          path: "C:\\Program Files\\dotnet\\myapp"  # Escaped backslashes

  deploy:
    runs-on: windows-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write # This is required for requesting the JWT

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: .net-app
      
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_5467E329587E45D4AA7E4B67C923D7F0 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_F83CD1A0206840AABB0640B489651D77 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_DD4ED051E0EE4A739FA6A08C79DA7DBC }}

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'Siyafunda'
          slot-name: 'Production'
          package: .  # Ensure this points to the published output
