name: .NET Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest  # Use Windows for .NET Framework

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Restore dependencies
        run: nuget restore ./SiyafundaApplication/SiyafundaApplication.sln  # Use NuGet for .NET Framework projects

      - name: Build project
        run: |
          & 'C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\MSBuild\Current\Bin\MSBuild.exe' ./SiyafundaApplication/SiyafundaApplication.sln /p:Configuration=Release

      - name: Run tests
        run: dotnet test ./SiyafundaApplication/SiyafundaApplication.sln --configuration Release
