name: Build and Deploy ASP.NET Framework App to Azure Web App - Siyafunda

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v1

      - name: Restore dependencies
        run: nuget restore ./SiyafundaApplication/SiyafundaApplication.sln

      - name: Build project
        run: msbuild ./SiyafundaApplication/SiyafundaApplication.sln /p:Configuration=Release

      - name: Create output directory
        run: mkdir -p ./publish-output  # Create the directory

      - name: Publish project
        run: msbuild ./SiyafundaApplication/SiyafundaApplication.sln /p:Configuration=Release /p:OutputPath=./publish-output /t:Publish

      - name: List published files
        run: dir ./publish-output

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: .net-app
          path: ./publish-output  # Path to the published files

  deploy:
    runs-on: windows-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write # This is required for requesting the JWT

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: .net-app
      
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_5467E329587E45D4AA7E4B67C923D7F0 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_F83CD1A0206840AABB0640B489651D77 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_DD4ED051E0EE4A739FA6A08C79DA7DBC }}

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'Siyafunda'
          slot-name: 'Production'
          package: './publish-output'  # Specify the path to the published files
