name: .NET Framework Build and Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest  # Ensure the runner is Windows

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v1

      - name: Restore dependencies
        run: nuget restore ./SiyafundaApplication/SiyafundaApplication.sln

      - name: Build project
        run: msbuild ./SiyafundaApplication/SiyafundaApplication.sln /p:Configuration=Release

      # Run tests using VSTest for .NET Framework projects
      #  - name: Run tests
      #  run: msbuild ./SiyafundaApplication/SiyafundaApplication.sln /t:VSTest /p:Configuration=Release

      # Optionally, for NUnit/xUnit tests
      # - name: Run tests
      #   run: dotnet test ./SiyafundaApplication/SiyafundaApplication.sln --configuration Release
